LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := Browser
LOCAL_CERTIFICATE := platform
LOCAL_MULTILIB := both
LOCAL_OVERRIDES_PACKAGES := Jelly

LOCAL_SRC_FILES := arm64_ChromeModernPublic.apk

LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
include $(BUILD_PREBUILT)
